// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIK0wfATWzAiAxIx4leA-PqKLBN94v1-8',
    appId: '1:622289822279:web:290d92fdb4a956cd564762',
    messagingSenderId: '622289822279',
    projectId: 'artfolio-5631d',
    authDomain: 'artfolio-5631d.firebaseapp.com',
    storageBucket: 'artfolio-5631d.appspot.com',
    measurementId: 'G-W2SBJ19EHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkOLXt0o8lrxcvEvj_g2Y_ocCqVz0DE4',
    appId: '1:622289822279:android:3774536a82da8f10564762',
    messagingSenderId: '622289822279',
    projectId: 'artfolio-5631d',
    storageBucket: 'artfolio-5631d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIK0wfATWzAiAxIx4leA-PqKLBN94v1-8',
    appId: '1:622289822279:web:1539865830e1afce564762',
    messagingSenderId: '622289822279',
    projectId: 'artfolio-5631d',
    authDomain: 'artfolio-5631d.firebaseapp.com',
    storageBucket: 'artfolio-5631d.appspot.com',
    measurementId: 'G-QKNR6S7M3N',
  );
}
